### ISSUE TITLE
Error: cannot open file: ptr_math

### ISSUE THREAD

**Issue by ghost** [adamsvoboda/nim-loader#2]
![image](https://user-images.githubusercontent.com/91875992/160899775-1ca47739-28f7-428f-a1be-028e25c2fbbf.png)

**Comment by adamsvoboda** [comment]
Ahh you will need to install it with nimble (nims package manager), its a third-party dependency:

`nimble install ptr_math`

**Comment by ghost** [comment]
worked, thanks
